const OK = 200
const CREATED = 201
const NO_CONTENT = 204
const BAD_REQUEST = 400
const UNAUTHORIZED = 401
const FORBIDDEN = 403
const NOT_FOUND = 404
const UNPROCESSABLE_ENTITY = 422
const TOO_MANY_REQUESTS = 429
const INTERNAL_SERVER_ERROR = 500
const PERMISSION_DENIED = 550
const INVALID_TOKEN = 551
const INVALID_CREDENTIALS = 552
const INVALID_REFRESH_TOKEN = 553

module.exports = {
  OK,
  CREATED,
  NO_CONTENT,
  BAD_REQUEST,
  UNAUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  UNPROCESSABLE_ENTITY,
  TOO_MANY_REQUESTS,
  INTERNAL_SERVER_ERROR,
  PERMISSION_DENIED,
  INVALID_TOKEN,
  INVALID_CREDENTIALS,
  INVALID_REFRESH_TOKEN
}
